### ISSUE TITLE
Issues when converting feature into BED12

### ISSUE THREAD

**Issue by hanfang** [daler/gffutils#96] opened 2017-07-09 19:23 UTC
Hi there,

We (me and @aemoor) recently ran into issues when converting `feature` into `BED12`

The error was from the function `FeatureDB.bed12`. When provided a mouse gtf file from Ensembl, the below error message occurred.

> `File "/Users/andreas/miniconda3/lib/python3.6/site-packages/gffutils/interface.py", line 1192, in bed12
% (last, feature.stop))
ValueError: End of last exon (91950640) does not match end of feature (91950725)

It seems like [line 1215-1217](https://github.com/daler/gffutils/blob/master/gffutils/interface.py#L1215-L1217) in `interface.py` is trying to validate whether the ends of the exon and the feature. Is this absolutely necessary? Is there a way to get around this? Thanks.

Han

**Comment by daler** [comment] 2017-07-10 14:42
This sounds like an error in the GTF. I think it is necessary to do this check, because the BED12 format expects the exon sizes to sum to the transcript size. What is the nature of that missing 85bp? An unannotated 3' UTR maybe?

The fix would be to manually add an annotation for that missing region. Alternatively, if it's already annotated, you may need to adjust the values of the `block_featuretype` argument to include it.

**Comment by hanfang** [comment] 2017-07-10 17:49
Thanks for the reply.

I think they are mostly unannotated 3' UTR, which are quite common in the Ensembl gtf files actually.

Instead of adding the 3' UTR, is it possible to restrict the output to `CDS`, i.e. ending at the last exon and excluding the 3' UTR? Thanks.

**Comment by daler** [comment] 2017-07-10 18:46
Let's see, this would require not using the annotated transcript boundaries but rather taking the extent of the `block_featuretype` features and using that for the transcript boundaries. In the problematic case we're talking about, this would truncate the annotated transcript lengths (basically favoring exon annotations rather than transcript start/stop). I think this is pretty reasonable as long as it's well-documented.

As for timeline, I have a lot on my plate at the moment, but I'd be happy to accept pull requests.

**Comment by mschatz** [comment] 2018-03-29 03:44
Can you please take a look at this? This would be very helpful for processing the human gencode annotation (such as https://www.gencodegenes.org/releases/19.html)

Here is a little snippet that triggers the error:

```
import gffutils
fn = gffutils.example_filename('gencode.v19.annotation.gtf')
db = gffutils.create_db(fn, ":memmory:", keep_order=True, disable_infer_genes=True, disable_infer_transcripts=True)

geneNames = []
for gene in db.features_of_type("CDS", order_by=("seqid","start")):
    geneNames.append(gene['gene_id'][0])

geneNames = list(set(geneNames))
geneBed12s = []
for geneName in geneNames:
    geneBed12 = db.bed12(geneName, name_field='gene_id')
    row = geneBed12.split("\t")
    geneBed12s.append([row[0], int(row[1]), int(row[2])] + row[3:])
```

And here is the reported error:
```
Traceback (most recent call last):
File "<stdin>", line 2, in <module>
File "/seq/schatz/bluearc_backup/schatz/mschatz/devel/scikitribo/scikit/lib/python2.7/site-packages/gffutils/interface.py",
line 1218, in bed12
% (last, feature.stop))
ValueError: End of last exon (57103347) does not match end of feature (57103351)
```

Thank you!

Mike

**Comment by daler** [comment] 2018-03-29 13:55
@mschatz (and @hanfang if you're still around, sorry that this slipped through the cracks):

Thanks for the example. I can reproduce the error using a subset of the GENCODE v19 GTF (chr11).

```bash
wget -O- \
  ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/gencode.v19.annotation.gtf \
  | zcat \
  | grep "^chr11" > chr11.gtf
```

However, your example asks for a BED12 line for an entire *gene* with possibly many transcripts. If I change `"gene_id"` in your example to `"transcript_id"`, it works as expected.

So, short answer: use `"transcript_id"`, not `"gene_id"`.

I actually don't know what the expected behavior should be for a BED12 line representing a gene with multiple transcripts. To investigate, here's an ASCII-art gene:

```
123456789012345
=====------====
  ===------====
```

The corresponding BED12 line -- with overlapping exons and the last exon duplicated -- is this:

```
chr1  1  15  .  0  +  1  15  0,0,0  4 4,5,3,3  0,2,11,11
```

Surprisingly to me, this actually worked as a custom track in UCSC. The Genome Browser displays the feature as a single transcript, sort of merging together the overlapping exons:

```
123456789012345
=====------====
  ===------====

=====------====  # UCSC visually represents it like this
```

The error you're seeing is because I've been assuming one BED12 line corresponds to one transcript with non-overlapping exons (this was pointed out in the [docstring](https://github.com/daler/gffutils/blob/v0.9/gffutils/interface.py#L1150), but could be a stronger warning). Specifically, your example code will cause the error on genes with multiple transcripts in which the the 3'-most exon of at least two transcripts are nested:

```
===---======
===-----==
```

I hesitate to rewrite the `bed12()` method to handle overlapping exons aggregated at the gene level because I feel like that's asking for downstream problems. While it looks like UCSC will display them correctly, downstream tools consuming the BED12 would need to handle this carefully (for example, it could get tricky to avoid double-counting the last exon in the first example above).

If the goal is to use gene-level BED12 lines with overlapping exons, would you describe how you're using them to help guide what the fix should be here?

**Comment by mschatz** [comment] 2018-04-02 02:51
Thanks for the update! Let us think about how to best handle this.

Thanks!

Mike

**Comment by daler** [comment] 2018-04-30 13:51
Closing this for now, as it's not clear how (or if) a single BED12 should should represent a gene with multiple transcripts.

**Closed by daler** 2018-04-30 13:51 UTC
